export const CHANGE_PASSWORD_PATH = "users/changePassword"
export const LOGIN_PATH = "auth/login"
export const ROLES_PATH = "roles"
export const USER_PATH = "users"
export const TRUCK_PATH = "trucks"
export const CITY_PATH = "cities"
